const bool _isReleaseMode = bool.fromEnvironment('dart.vm.product');

enum JokerRarity { common, uncommon, rare, wild }

enum JokerEffect {
  /// Owner-only test effect. Never reachable from a release build.
  devTwentyX,
  copperChip,
  suitPresser,
  royalRetainer,
  evenOdds,
  aceMagnet,
  lowBall,
  pairPolisher,
  flushFund,
  straightWire,
  momentum,
  suitUniform,
  highRoller,
  pairTrainer,
  lastCall,
  inkTrade,
  tripleThreat,
  dumpsterValue,
  dividend,
  powerCouple,
  sniper,
  fullTable,
  deckMiser,
  overtime,
  butcher,
  collector,
  boostFiend,
  piggyBank,
  moddedOut,
  tailor,
  heatSurge,
  survivor,
  cleaner,
  printer,
  royalScam,
  luckySeven,
  doubleDown,
  allIn,
  shortcut,
  pocketFlush,
  theCheat,
  practiceMode,
  openingAct,
  clutchGear,
  numberStation,
  coldAdapter,
  frequencyMeter,
  panicButton,
  stormHarness,
  encore,
  guillotine,
  redline,
  colorWash,
  masterClass,
  dangerMusic,
  rehearsalTape,
  prismLens,
  glassJoystick,
  icePick,
  unionBoss,
  gravedigger,
  roseTint,
  oddJob,
  primeTime,
  kingpin,
  twinFlame,
  trident,
  quartet,
  faceValue,
  aceInTheHole,
  rainbow,
  underdog,
  frontrunner,
  marathoner,
  metronome,
  perfectionist,
  comboist,
  goldsmith,
  neonDealer,
  glazier,
  wildWhisperer,
  purist,
  hoarder,
  monochrome,
  twinStudy,
  closer,
  leadoff,
  ensemble,
  rarityHunter,
  warmUp,
  overclock,
  roulette,
  bloodMoney,
  fragileGenius,
  highWire,
  chaosTheory,
  ruleBreaker,
  safeCracker,
  gapFiller,
  twoFaced,
  understudy,
  suitSwap,
  alchemist,
}

class JokerDefinition {
  const JokerDefinition({
    required this.id,
    required this.name,
    required this.rarity,
    required this.description,
    required this.price,
    required this.unlock,
    required this.effect,
    this.starter = false,
    this.stateKey,
  });

  final String id;
  final String name;
  final JokerRarity rarity;
  final String description;
  final int price;
  final int unlock;
  final JokerEffect effect;
  final bool starter;
  final String? stateKey;

  int get collectionUnlockCost {
    if (unlock == 0) return 0;
    final multiplier = switch (rarity) {
      JokerRarity.common => 1.5,
      JokerRarity.uncommon => 2.2,
      JokerRarity.rare => 2.7,
      JokerRarity.wild => 3.0,
    };
    return ((unlock * multiplier) / 5).round() * 5;
  }

  int get startBoostPrice => switch (rarity) {
    JokerRarity.common => 6,
    JokerRarity.uncommon => 10,
    JokerRarity.rare => 16,
    JokerRarity.wild => 30,
  };
}

const List<JokerDefinition> jokerCatalog = <JokerDefinition>[
  JokerDefinition(
    id: 'copper',
    name: 'Copper Chip',
    rarity: JokerRarity.common,
    description: '+0.20 Multiplier, always.',
    price: 4,
    unlock: 0,
    starter: true,
    effect: JokerEffect.copperChip,
  ),
  JokerDefinition(
    id: 'presser',
    name: 'Suit Presser',
    rarity: JokerRarity.common,
    description: 'Hearts count +4 rank.',
    price: 4,
    unlock: 0,
    starter: true,
    effect: JokerEffect.suitPresser,
  ),
  JokerDefinition(
    id: 'retainer',
    name: 'Royal Retainer',
    rarity: JokerRarity.common,
    description: 'Face cards (J, Q, K) count +5 rank.',
    price: 5,
    unlock: 0,
    starter: true,
    effect: JokerEffect.royalRetainer,
  ),
  JokerDefinition(
    id: 'even',
    name: 'Even Odds',
    rarity: JokerRarity.common,
    description: 'Even-ranked cards count +3 rank.',
    price: 4,
    unlock: 0,
    starter: true,
    effect: JokerEffect.evenOdds,
  ),
  JokerDefinition(
    id: 'acemag',
    name: 'Ace Magnet',
    rarity: JokerRarity.common,
    description: 'Aces count +10 extra rank (25 total).',
    price: 5,
    unlock: 45,
    effect: JokerEffect.aceMagnet,
  ),
  JokerDefinition(
    id: 'lowball',
    name: 'Low Ball',
    rarity: JokerRarity.common,
    description: 'Cards ranked 6 or lower count double rank.',
    price: 5,
    unlock: 0,
    starter: true,
    effect: JokerEffect.lowBall,
  ),
  JokerDefinition(
    id: 'polish',
    name: 'Pair Polisher',
    rarity: JokerRarity.uncommon,
    description: '×1.4 Multiplier if the hand is Pair or better.',
    price: 6,
    unlock: 0,
    starter: true,
    effect: JokerEffect.pairPolisher,
  ),
  JokerDefinition(
    id: 'flushfund',
    name: 'Flush Fund',
    rarity: JokerRarity.wild,
    description: '×1.8 Multiplier on Flush hands.',
    price: 10,
    unlock: 60,
    effect: JokerEffect.flushFund,
  ),
  JokerDefinition(
    id: 'wire',
    name: 'Straight Wire',
    rarity: JokerRarity.uncommon,
    description: '×1.8 Multiplier on Straight hands.',
    price: 7,
    unlock: 60,
    effect: JokerEffect.straightWire,
  ),
  JokerDefinition(
    id: 'momentum',
    name: 'Momentum',
    rarity: JokerRarity.uncommon,
    description: '+0.10 Multiplier per hand already played this Heat.',
    price: 6,
    unlock: 55,
    effect: JokerEffect.momentum,
  ),
  JokerDefinition(
    id: 'uniform',
    name: 'Suit Uniform',
    rarity: JokerRarity.uncommon,
    description: '+0.50 Multiplier if all played cards share one colour.',
    price: 6,
    unlock: 0,
    starter: true,
    effect: JokerEffect.suitUniform,
  ),
  JokerDefinition(
    id: 'roller',
    name: 'High Roller',
    rarity: JokerRarity.uncommon,
    description: '×1.25 Multiplier, always.',
    price: 7,
    unlock: 80,
    effect: JokerEffect.highRoller,
  ),
  JokerDefinition(
    id: 'trainer',
    name: 'Pair Trainer',
    rarity: JokerRarity.wild,
    description:
        'Gains +0.05 Multiplier permanently each time you score Pair or better this run.',
    price: 10,
    unlock: 70,
    stateKey: 'trainer',
    effect: JokerEffect.pairTrainer,
  ),
  JokerDefinition(
    id: 'lastcall',
    name: 'Last Call',
    rarity: JokerRarity.rare,
    description: '×3 Multiplier on the final play of a Heat.',
    price: 8,
    unlock: 80,
    effect: JokerEffect.lastCall,
  ),
  JokerDefinition(
    id: 'inktrade',
    name: 'Ink Trade',
    rarity: JokerRarity.common,
    description: 'Black cards count +3 rank.',
    price: 5,
    unlock: 40,
    effect: JokerEffect.inkTrade,
  ),
  JokerDefinition(
    id: 'triple3',
    name: 'Triple Threat',
    rarity: JokerRarity.common,
    description: 'Every 3 scores triple rank.',
    price: 4,
    unlock: 0,
    starter: true,
    effect: JokerEffect.tripleThreat,
  ),
  JokerDefinition(
    id: 'dumpster',
    name: 'Dumpster Value',
    rarity: JokerRarity.uncommon,
    description: '+0.08 Multiplier per discard used this Heat.',
    price: 6,
    unlock: 45,
    effect: JokerEffect.dumpsterValue,
  ),
  JokerDefinition(
    id: 'dividend',
    name: 'Dividend',
    rarity: JokerRarity.uncommon,
    description: '+2 run coins every time you clear a Heat.',
    price: 6,
    unlock: 55,
    effect: JokerEffect.dividend,
  ),
  JokerDefinition(
    id: 'couple',
    name: 'Power Couple',
    rarity: JokerRarity.uncommon,
    description:
        '×1.6 Multiplier if the played cards include an Ace and a King.',
    price: 6,
    unlock: 65,
    effect: JokerEffect.powerCouple,
  ),
  JokerDefinition(
    id: 'sniper',
    name: 'Sniper',
    rarity: JokerRarity.common,
    description: '×2.2 Multiplier when you play exactly 1 card.',
    price: 5,
    unlock: 65,
    effect: JokerEffect.sniper,
  ),
  JokerDefinition(
    id: 'fulltable',
    name: 'Full Table',
    rarity: JokerRarity.common,
    description: '+0.40 Multiplier when you play all 5 cards.',
    price: 5,
    unlock: 0,
    starter: true,
    effect: JokerEffect.fullTable,
  ),
  JokerDefinition(
    id: 'miser',
    name: 'Deck Miser',
    rarity: JokerRarity.rare,
    description: '+0.02 Multiplier per card still in the deck.',
    price: 8,
    unlock: 70,
    effect: JokerEffect.deckMiser,
  ),
  JokerDefinition(
    id: 'overtime',
    name: 'Overtime',
    rarity: JokerRarity.uncommon,
    description: '+0.15 Multiplier per Heat above 9.',
    price: 7,
    unlock: 100,
    effect: JokerEffect.overtime,
  ),
  JokerDefinition(
    id: 'butcher',
    name: 'Butcher',
    rarity: JokerRarity.uncommon,
    description: '+0.50 Multiplier per card destroyed from your deck this run.',
    price: 7,
    unlock: 90,
    effect: JokerEffect.butcher,
  ),
  JokerDefinition(
    id: 'collector',
    name: 'Collector',
    rarity: JokerRarity.uncommon,
    description: '+0.04 Multiplier per card added to your deck this run.',
    price: 6,
    unlock: 65,
    effect: JokerEffect.collector,
  ),
  JokerDefinition(
    id: 'boostfiend',
    name: 'Boost Fiend',
    rarity: JokerRarity.uncommon,
    description: '×1.3 Multiplier if the played hand type has been Boosted.',
    price: 6,
    unlock: 70,
    effect: JokerEffect.boostFiend,
  ),
  JokerDefinition(
    id: 'piggy',
    name: 'Piggy Bank',
    rarity: JokerRarity.uncommon,
    description: '+0.05 Multiplier per 5 run coins you hold.',
    price: 6,
    unlock: 45,
    effect: JokerEffect.piggyBank,
  ),
  JokerDefinition(
    id: 'modded',
    name: 'Modded Out',
    rarity: JokerRarity.rare,
    description: '×1.5 Multiplier during Heat Modifier Heats.',
    price: 8,
    unlock: 95,
    effect: JokerEffect.moddedOut,
  ),
  JokerDefinition(
    id: 'tailor',
    name: 'Tailor',
    rarity: JokerRarity.rare,
    description: '×1.4 Multiplier if your deck has 5+ cards of the same rank.',
    price: 8,
    unlock: 70,
    effect: JokerEffect.tailor,
  ),
  JokerDefinition(
    id: 'surge',
    name: 'Heat Surge',
    rarity: JokerRarity.wild,
    description: '+0.20 Multiplier for each Heat cleared this run.',
    price: 10,
    unlock: 110,
    effect: JokerEffect.heatSurge,
  ),
  JokerDefinition(
    id: 'survivor',
    name: 'Survivor',
    rarity: JokerRarity.wild,
    description: '×2 Multiplier if this Heat has a modifier.',
    price: 10,
    unlock: 120,
    effect: JokerEffect.survivor,
  ),
  JokerDefinition(
    id: 'cleaner',
    name: 'Cleaner',
    rarity: JokerRarity.common,
    description: '+0.25 Multiplier if your deck has fewer than 45 cards.',
    price: 5,
    unlock: 70,
    effect: JokerEffect.cleaner,
  ),
  JokerDefinition(
    id: 'printer',
    name: 'Printer',
    rarity: JokerRarity.common,
    description: '+0.10 Multiplier per copied card in your deck.',
    price: 5,
    unlock: 100,
    effect: JokerEffect.printer,
  ),
  JokerDefinition(
    id: 'royalscam',
    name: 'Royal Scam',
    rarity: JokerRarity.common,
    description: 'J, Q and K score twice.',
    price: 5,
    unlock: 100,
    effect: JokerEffect.royalScam,
  ),
  JokerDefinition(
    id: 'lucky7',
    name: 'Lucky Seven',
    rarity: JokerRarity.common,
    description: 'Each scoring 7 has a 33% chance to score ×10.',
    price: 5,
    unlock: 100,
    effect: JokerEffect.luckySeven,
  ),
  JokerDefinition(
    id: 'doubledown',
    name: 'Double Down',
    rarity: JokerRarity.rare,
    description:
        '×2 Multiplier if this hand type matches your previous play this Heat.',
    price: 8,
    unlock: 110,
    effect: JokerEffect.doubleDown,
  ),
  JokerDefinition(
    id: 'allin',
    name: 'All In',
    rarity: JokerRarity.rare,
    description: 'Final play of a Heat scores ×4 — earlier plays score ×0.75.',
    price: 8,
    unlock: 120,
    effect: JokerEffect.allIn,
  ),
  JokerDefinition(
    id: 'shortcut',
    name: 'Shortcut',
    rarity: JokerRarity.common,
    description: '3-card Straights count as Straights.',
    price: 5,
    unlock: 160,
    effect: JokerEffect.shortcut,
  ),
  JokerDefinition(
    id: 'pocketflush',
    name: 'Pocket Flush',
    rarity: JokerRarity.uncommon,
    description: '4-card Flushes count as Flushes.',
    price: 7,
    unlock: 160,
    effect: JokerEffect.pocketFlush,
  ),
  JokerDefinition(
    id: 'cheat',
    name: 'The Cheat',
    rarity: JokerRarity.uncommon,
    description: 'You may play 6 cards. The best 5 form the hand.',
    price: 6,
    unlock: 200,
    effect: JokerEffect.theCheat,
  ),
  JokerDefinition(
    id: 'practice_mode',
    name: 'Practice Mode',
    rarity: JokerRarity.common,
    description: '+0.15 Multiplier for each hand type you have Boosted.',
    price: 5,
    unlock: 40,
    effect: JokerEffect.practiceMode,
  ),
  JokerDefinition(
    id: 'opening_act',
    name: 'Opening Act',
    rarity: JokerRarity.common,
    description: '+0.50 Multiplier on the first hand of each Heat.',
    price: 5,
    unlock: 0,
    starter: true,
    effect: JokerEffect.openingAct,
  ),
  JokerDefinition(
    id: 'clutch_gear',
    name: 'Clutch Gear',
    rarity: JokerRarity.uncommon,
    description: '+0.60 Multiplier when only 1 play remains.',
    price: 6,
    unlock: 40,
    effect: JokerEffect.clutchGear,
  ),
  JokerDefinition(
    id: 'number_station',
    name: 'Number Station',
    rarity: JokerRarity.common,
    description: '2s, 3s and 4s count +4 rank.',
    price: 4,
    unlock: 35,
    effect: JokerEffect.numberStation,
  ),
  JokerDefinition(
    id: 'cold_adapter',
    name: 'Cold Adapter',
    rarity: JokerRarity.common,
    description: '+0.30 Multiplier during a Cold Deck Heat.',
    price: 4,
    unlock: 35,
    effect: JokerEffect.coldAdapter,
  ),
  JokerDefinition(
    id: 'frequency_meter',
    name: 'Frequency Meter',
    rarity: JokerRarity.uncommon,
    description:
        '×1.4 Multiplier if your deck has one most common rank and you play it.',
    price: 7,
    unlock: 60,
    effect: JokerEffect.frequencyMeter,
  ),
  JokerDefinition(
    id: 'panic_button',
    name: 'Panic Button',
    rarity: JokerRarity.uncommon,
    description: '×1.4 Multiplier while you have 0 discards left.',
    price: 6,
    unlock: 60,
    effect: JokerEffect.panicButton,
  ),
  JokerDefinition(
    id: 'storm_harness',
    name: 'Storm Harness',
    rarity: JokerRarity.rare,
    description: '×1.4 Multiplier during any Heat Modifier.',
    price: 8,
    unlock: 60,
    effect: JokerEffect.stormHarness,
  ),
  JokerDefinition(
    id: 'encore',
    name: 'Encore',
    rarity: JokerRarity.uncommon,
    description:
        '+0.30 Multiplier if this hand type matches your last play this Heat.',
    price: 6,
    unlock: 55,
    effect: JokerEffect.encore,
  ),
  JokerDefinition(
    id: 'guillotine',
    name: 'Guillotine',
    rarity: JokerRarity.common,
    description: '×1.5 Multiplier while your deck has fewer than 42 cards.',
    price: 5,
    unlock: 65,
    effect: JokerEffect.guillotine,
  ),
  JokerDefinition(
    id: 'redline',
    name: 'Redline',
    rarity: JokerRarity.uncommon,
    description: '×2.5 Multiplier once this Heat is 55% cleared.',
    price: 7,
    unlock: 110,
    effect: JokerEffect.redline,
  ),
  JokerDefinition(
    id: 'color_wash',
    name: 'Color Wash',
    rarity: JokerRarity.rare,
    description: '+0.45 Multiplier if every played card is one colour.',
    price: 8,
    unlock: 100,
    effect: JokerEffect.colorWash,
  ),
  JokerDefinition(
    id: 'master_class',
    name: 'Master Class',
    rarity: JokerRarity.rare,
    description: '×1.15 Multiplier per Boost level on the played hand type.',
    price: 8,
    unlock: 110,
    effect: JokerEffect.masterClass,
  ),
  JokerDefinition(
    id: 'danger_music',
    name: 'Danger Music',
    rarity: JokerRarity.rare,
    description:
        '×1.35 Multiplier, stacking, for every hand already played this Heat.',
    price: 9,
    unlock: 190,
    effect: JokerEffect.dangerMusic,
  ),
  JokerDefinition(
    id: 'rehearsal_tape',
    name: 'Rehearsal Tape',
    rarity: JokerRarity.uncommon,
    description: '×1.3 Multiplier on the first hand of each Heat.',
    price: 7,
    unlock: 180,
    effect: JokerEffect.rehearsalTape,
  ),
  JokerDefinition(
    id: 'prism_lens',
    name: 'Prism Lens',
    rarity: JokerRarity.rare,
    description: '×1.35 Multiplier when 5+ played cards share one colour.',
    price: 8,
    unlock: 190,
    effect: JokerEffect.prismLens,
  ),
  JokerDefinition(
    id: 'glass_joystick',
    name: 'Glass Joystick',
    rarity: JokerRarity.uncommon,
    description:
        '×3 Multiplier. Survives its first Heat, then has a 1 in 6 chance to shatter on later clears.',
    price: 7,
    unlock: 200,
    stateKey: 'glass_joystick_armed',
    effect: JokerEffect.glassJoystick,
  ),
  JokerDefinition(
    id: 'ice_pick',
    name: 'Ice Pick',
    rarity: JokerRarity.common,
    description: 'Diamonds count +4 rank.',
    price: 4,
    unlock: 35,
    effect: JokerEffect.icePick,
  ),
  JokerDefinition(
    id: 'union_boss',
    name: 'Union Boss',
    rarity: JokerRarity.common,
    description: 'Clubs count +4 rank.',
    price: 4,
    unlock: 35,
    effect: JokerEffect.unionBoss,
  ),
  JokerDefinition(
    id: 'gravedigger',
    name: 'Gravedigger',
    rarity: JokerRarity.common,
    description: 'Spades count +4 rank.',
    price: 4,
    unlock: 35,
    effect: JokerEffect.gravedigger,
  ),
  JokerDefinition(
    id: 'rose_tint',
    name: 'Rose Tint',
    rarity: JokerRarity.common,
    description: 'Red cards count +3 rank.',
    price: 5,
    unlock: 40,
    effect: JokerEffect.roseTint,
  ),
  JokerDefinition(
    id: 'odd_job',
    name: 'Odd Job',
    rarity: JokerRarity.common,
    description: 'Odd-ranked cards count +3 rank.',
    price: 5,
    unlock: 40,
    effect: JokerEffect.oddJob,
  ),
  JokerDefinition(
    id: 'prime_time',
    name: 'Prime Time',
    rarity: JokerRarity.common,
    description: 'Ranks 2, 3, 5 and 7 count +4 rank.',
    price: 5,
    unlock: 55,
    effect: JokerEffect.primeTime,
  ),
  JokerDefinition(
    id: 'kingpin',
    name: 'Kingpin',
    rarity: JokerRarity.common,
    description: 'Kings count +8 rank.',
    price: 5,
    unlock: 60,
    effect: JokerEffect.kingpin,
  ),
  JokerDefinition(
    id: 'twin_flame',
    name: 'Twin Flame',
    rarity: JokerRarity.common,
    description: '×1.5 Multiplier when exactly 2 cards are played.',
    price: 5,
    unlock: 40,
    effect: JokerEffect.twinFlame,
  ),
  JokerDefinition(
    id: 'trident',
    name: 'Trident',
    rarity: JokerRarity.common,
    description: '×1.7 Multiplier when exactly 3 cards are played.',
    price: 5,
    unlock: 55,
    effect: JokerEffect.trident,
  ),
  JokerDefinition(
    id: 'quartet',
    name: 'Quartet',
    rarity: JokerRarity.common,
    description: '×1.6 Multiplier when exactly 4 cards are played.',
    price: 5,
    unlock: 55,
    effect: JokerEffect.quartet,
  ),
  JokerDefinition(
    id: 'face_value',
    name: 'Face Value',
    rarity: JokerRarity.rare,
    description: '×1.5 Multiplier when the hand contains a J, Q or K.',
    price: 8,
    unlock: 45,
    effect: JokerEffect.faceValue,
  ),
  JokerDefinition(
    id: 'ace_in_the_hole',
    name: 'Ace In The Hole',
    rarity: JokerRarity.uncommon,
    description: '×1.6 Multiplier when the hand contains an Ace.',
    price: 6,
    unlock: 60,
    effect: JokerEffect.aceInTheHole,
  ),
  JokerDefinition(
    id: 'rainbow',
    name: 'Rainbow',
    rarity: JokerRarity.uncommon,
    description: '×2 Multiplier when played cards span 3+ suits.',
    price: 7,
    unlock: 100,
    effect: JokerEffect.rainbow,
  ),
  JokerDefinition(
    id: 'underdog',
    name: 'Underdog',
    rarity: JokerRarity.rare,
    description: '×2 Multiplier while Heat score is below 40% of target.',
    price: 8,
    unlock: 65,
    effect: JokerEffect.underdog,
  ),
  JokerDefinition(
    id: 'frontrunner',
    name: 'Frontrunner',
    rarity: JokerRarity.common,
    description: '×1.6 Multiplier while Heat score is above 80% of target.',
    price: 5,
    unlock: 65,
    effect: JokerEffect.frontrunner,
  ),
  JokerDefinition(
    id: 'marathoner',
    name: 'Marathoner',
    rarity: JokerRarity.rare,
    description: '+0.20 Multiplier per play remaining this Heat.',
    price: 8,
    unlock: 45,
    effect: JokerEffect.marathoner,
  ),
  JokerDefinition(
    id: 'metronome',
    name: 'Metronome',
    rarity: JokerRarity.uncommon,
    description: '+0.30 Multiplier per consecutive same-type hand.',
    price: 7,
    unlock: 70,
    stateKey: 'metronome',
    effect: JokerEffect.metronome,
  ),
  JokerDefinition(
    id: 'perfectionist',
    name: 'Perfectionist',
    rarity: JokerRarity.rare,
    description: '×2.5 Multiplier while every hand this Heat is one type.',
    price: 8,
    unlock: 110,
    stateKey: 'perfect',
    effect: JokerEffect.perfectionist,
  ),
  JokerDefinition(
    id: 'comboist',
    name: 'Comboist',
    rarity: JokerRarity.uncommon,
    description: '+0.15 Multiplier per distinct hand type this Heat.',
    price: 7,
    unlock: 70,
    stateKey: 'combo',
    effect: JokerEffect.comboist,
  ),
  JokerDefinition(
    id: 'goldsmith',
    name: 'Goldsmith',
    rarity: JokerRarity.common,
    description: '×1.5 Multiplier when any played card is Gilded.',
    price: 5,
    unlock: 65,
    effect: JokerEffect.goldsmith,
  ),
  JokerDefinition(
    id: 'neon_dealer',
    name: 'Neon Dealer',
    rarity: JokerRarity.common,
    description: '+0.40 Multiplier per Neon card played.',
    price: 5,
    unlock: 60,
    effect: JokerEffect.neonDealer,
  ),
  JokerDefinition(
    id: 'glazier',
    name: 'Glazier',
    rarity: JokerRarity.common,
    description: 'Glass cards score ×3 rank.',
    price: 5,
    unlock: 105,
    effect: JokerEffect.glazier,
  ),
  JokerDefinition(
    id: 'wild_whisperer',
    name: 'Wild Whisperer',
    rarity: JokerRarity.uncommon,
    description: '×1.35 Multiplier per Wild-suit card played.',
    price: 7,
    unlock: 110,
    effect: JokerEffect.wildWhisperer,
  ),
  JokerDefinition(
    id: 'purist',
    name: 'Purist',
    rarity: JokerRarity.wild,
    description: '×1.6 Multiplier when no played card is enhanced.',
    price: 10,
    unlock: 65,
    effect: JokerEffect.purist,
  ),
  JokerDefinition(
    id: 'hoarder',
    name: 'Hoarder',
    rarity: JokerRarity.uncommon,
    description: '+0.03 Multiplier per deck card over 40.',
    price: 6,
    unlock: 50,
    effect: JokerEffect.hoarder,
  ),
  JokerDefinition(
    id: 'monochrome',
    name: 'Monochrome',
    rarity: JokerRarity.uncommon,
    description: '×1.7 Multiplier when 60%+ of the deck is one colour.',
    price: 7,
    unlock: 105,
    effect: JokerEffect.monochrome,
  ),
  JokerDefinition(
    id: 'twin_study',
    name: 'Twin Study',
    rarity: JokerRarity.common,
    description: '×1.4 Multiplier with 4+ ranks held as exact pairs.',
    price: 5,
    unlock: 70,
    effect: JokerEffect.twinStudy,
  ),
  JokerDefinition(
    id: 'closer',
    name: 'Closer',
    rarity: JokerRarity.common,
    description: 'The last scoring card scores ×3 rank.',
    price: 5,
    unlock: 65,
    effect: JokerEffect.closer,
  ),
  JokerDefinition(
    id: 'leadoff',
    name: 'Leadoff',
    rarity: JokerRarity.common,
    description: 'The first scoring card scores +6 rank.',
    price: 5,
    unlock: 40,
    effect: JokerEffect.leadoff,
  ),
  JokerDefinition(
    id: 'ensemble',
    name: 'Ensemble',
    rarity: JokerRarity.rare,
    description: '+0.12 Multiplier per Joker held, including itself.',
    price: 8,
    unlock: 60,
    effect: JokerEffect.ensemble,
  ),
  JokerDefinition(
    id: 'rarity_hunter',
    name: 'Rarity Hunter',
    rarity: JokerRarity.common,
    description: '×1.25 Multiplier per Rare or Wild Joker held.',
    price: 5,
    unlock: 110,
    effect: JokerEffect.rarityHunter,
  ),
  JokerDefinition(
    id: 'warm_up',
    name: 'Warm-Up',
    rarity: JokerRarity.uncommon,
    description: '+0.60 Multiplier on the first hand of each Heat.',
    price: 6,
    unlock: 45,
    effect: JokerEffect.warmUp,
  ),
  JokerDefinition(
    id: 'overclock',
    name: 'Overclock',
    rarity: JokerRarity.wild,
    description: '×3 Multiplier, but each Heat starts with 1 fewer play.',
    price: 10,
    unlock: 115,
    effect: JokerEffect.overclock,
  ),
  JokerDefinition(
    id: 'roulette',
    name: 'Roulette',
    rarity: JokerRarity.rare,
    description: 'Each hand has a 50% ×2.5 or 50% ×0.6 Multiplier.',
    price: 8,
    unlock: 115,
    effect: JokerEffect.roulette,
  ),
  JokerDefinition(
    id: 'blood_money',
    name: 'Blood Money',
    rarity: JokerRarity.wild,
    description: '×1.8 Multiplier; every play costs 1 run coin.',
    price: 10,
    unlock: 75,
    effect: JokerEffect.bloodMoney,
  ),
  JokerDefinition(
    id: 'fragile_genius',
    name: 'Fragile Genius',
    rarity: JokerRarity.common,
    description: '×4 Multiplier; shatters if a hand scores below the last.',
    price: 5,
    unlock: 200,
    stateKey: 'fragile',
    effect: JokerEffect.fragileGenius,
  ),
  JokerDefinition(
    id: 'high_wire',
    name: 'High Wire',
    rarity: JokerRarity.uncommon,
    description: '×2.2 Multiplier with 0 discards and 1 play left.',
    price: 6,
    unlock: 115,
    effect: JokerEffect.highWire,
  ),
  JokerDefinition(
    id: 'chaos_theory',
    name: 'Chaos Theory',
    rarity: JokerRarity.rare,
    description: '+0.50 Multiplier per active Heat modifier.',
    price: 8,
    unlock: 65,
    effect: JokerEffect.chaosTheory,
  ),
  JokerDefinition(
    id: 'rule_breaker',
    name: 'Rule Breaker',
    rarity: JokerRarity.wild,
    description: '×2.2 Multiplier during a THE HOUSE Heat.',
    price: 10,
    unlock: 120,
    effect: JokerEffect.ruleBreaker,
  ),
  JokerDefinition(
    id: 'safe_cracker',
    name: 'Safe Cracker',
    rarity: JokerRarity.rare,
    description: '+0.35 Multiplier per modifier survived this run.',
    price: 9,
    unlock: 75,
    stateKey: 'safecrack',
    effect: JokerEffect.safeCracker,
  ),
  JokerDefinition(
    id: 'gap_filler',
    name: 'Gap Filler',
    rarity: JokerRarity.common,
    description: 'Straights may skip one rank.',
    price: 5,
    unlock: 190,
    effect: JokerEffect.gapFiller,
  ),
  JokerDefinition(
    id: 'two_faced',
    name: 'Two-Faced',
    rarity: JokerRarity.common,
    description: 'Two Pair uses the Full House base score.',
    price: 5,
    unlock: 110,
    effect: JokerEffect.twoFaced,
  ),
  JokerDefinition(
    id: 'understudy',
    name: 'Understudy',
    rarity: JokerRarity.uncommon,
    description: 'The highest card counts twice for hand detection.',
    price: 7,
    unlock: 200,
    effect: JokerEffect.understudy,
  ),
  JokerDefinition(
    id: 'suit_swap',
    name: 'Suit Swap',
    rarity: JokerRarity.rare,
    description: 'One played card counts as any suit for Flushes.',
    price: 8,
    unlock: 115,
    effect: JokerEffect.suitSwap,
  ),
  JokerDefinition(
    id: 'alchemist',
    name: 'Alchemist',
    rarity: JokerRarity.common,
    description: '2s count as Aces for rank and pairing.',
    price: 5,
    unlock: 120,
    effect: JokerEffect.alchemist,
  ),
];

/// Counts only Jokers that exist in this public build.
///
/// Older developer saves can legitimately contain a test-only Joker ID. Keep
/// that unknown ID round-trippable, but do not let it produce `103 / 102`, alter
/// chest newcomer pricing or advance public collection gates.
int publicUnlockedJokerCount(Iterable<String> ownedIds) {
  final owned = ownedIds is Set<String> ? ownedIds : ownedIds.toSet();
  return jokerCatalog.where((joker) => owned.contains(joker.id)).length;
}

/// Owner-only test Joker. Deliberately NOT part of [jokerCatalog]: the public
/// catalogue stays at 102 and `publicUnlockedJokerCount` keeps ignoring it, so
/// collection counts and their tests are unaffected. It exists purely so the
/// owner can reach late Heats, the Heat 12 cinematic and Endless quickly.
const JokerDefinition devTwentyXJoker = JokerDefinition(
  id: 'devx20',
  name: 'DEV ×20',
  rarity: JokerRarity.wild,
  description: 'DEV: ×20 Multiplier, always. Owner test build only.',
  price: 0,
  unlock: 0,
  effect: JokerEffect.devTwentyX,
);

/// True for debug and profile builds, false for release. A Play build can
/// therefore never surface the Joker, and the id is dropped from any save it
/// loads because it is absent from the catalogue.
bool get devJokerAvailable => !_isReleaseMode;

final Map<String, JokerDefinition> jokersById = <String, JokerDefinition>{
  for (final joker in jokerCatalog) joker.id: joker,
  if (devJokerAvailable) devTwentyXJoker.id: devTwentyXJoker,
};

/// Jokers offerable as a start boost: the public catalogue, plus the owner
/// test Joker on non-release builds.
List<JokerDefinition> get selectableJokers => <JokerDefinition>[
  if (devJokerAvailable) devTwentyXJoker,
  ...jokerCatalog,
];

const List<String> starterJokerIds = <String>[
  'copper',
  'presser',
  'retainer',
  'even',
  'lowball',
  'uniform',
  'triple3',
  'fulltable',
  'polish',
  'opening_act',
];

const Map<JokerRarity, double> jokerShopRarityWeights = <JokerRarity, double>{
  JokerRarity.common: 4,
  JokerRarity.uncommon: 3.2,
  JokerRarity.rare: 3,
  JokerRarity.wild: 1.8,
};

const int wildPityAfterShops = 6;
